### ISSUE TITLE
missing cython dependency

### ISSUE THREAD

**Issue by kmnip** [LRGASP/lrgasp-challenge-3-evaluation#2]
Hi,

I was trying to install the evaluation tools based on the instructions described on the readme page.
Squanti3 was installed fine, but I encountered an error while building cDNA_Cupcake:
```
(sqanti3_lrgasp) $ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
``` 
After installing `cython` with `conda install cython`, I was able to build and install cupcake successfully.
So, `cython` needs to be added to the dependencies listed in `sqanti3_lrgasp.yml`.

Thanks,
Ka Ming

**Comment by FJPardoPalacios** [comment]
Sorry about that. I just included `cython` into the YML file.

Thank you!
Fran
